version: '2'
services:
  web:
    image: nicopaez/password-api:latest
    expose:
      - "3000"
  balancer:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "3001:3001"
